# URL Root
BaseURL = "/"

# Site title
title = "Enectiva FAQ"

# Language
LanguageCode = "en"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = "true"
disableLanguages = ["fr", "ru", "de", "it"]

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Pagination
paginate = 6
paginatePath = "page"

[params]
    author = "Enectiva"
    search = true
    stylesheets = [
        "dist/main.min.css",
        "assets/css/fonts.min.css",
        "assets/css/flags.min.css"
    ]
    
    javascript = [
        "jquery-3.2.1.js",
        "horsey.min.js",
        "lunr.min.js",
        "string.min.js",
        "main.js"
    ]
    headerlogo = "assets/img/logo.png"
    footerlogo = "assets/img/enerfis-logo.png"

[taxonomies]
    tag     = "tags"
    czech   = "cs"
    english = "en"
    german  = "de"
    italian = "it"
    russian = "ru"
    spanish = "es"
    french  = "fr"

[permalinks]
    es = "/:slug/:filename"
    cs = "/:slug/:filename"
    it = "/:slug/:filename"
    de = "/:slug/:filename"
    en = "/:slug/:filename"
    ru = "/:slug/:filename"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[outputs]
    home = [
        "HTML"
    ]
    taxonomy = [
        "HTML", "JSON"
    ]
    page = [
        "HTML"
    ]

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[languages]
    [languages.cs]
        contentDir = "content/cs"
        languageName = "Czech"
        weight = 1
    [languages.en]
        contentDir = "content/en"
        languageName = "English"
        weight = 2
    [languages.es]
        contentDir = "content/es"
        languageName = "Spanish"
        weight = 3
    [languages.it]
        contentDir = "content/it"
        languageName = "Italian"
        weight = 4
    [languages.de]
        contentDir = "content/de"
	languageName = "German"
	weight = 5
    [languages.ru]
	contentDir = "content/ru"
	languageName = "Russian
	weight = 6
    [language.fr]
        contentDir = "content/fr"
        languageName = "French"
        weight = 7
