# URL Root
BaseURL = "/"

# Site title
title = "Enectiva FAQ"

# Language
LanguageCode = "cs"
DefaultContentLanguage = "cs"
DefaultContentLanguageInSubdir = "true"
disableLanguages = ["fr", "ru", "de", "it"]

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Pagination
paginate = 6
paginatePath = "page"

[params]
    author = "Enectiva"
    search = true
    search_server = "http://192.168.1.150:3000/"
    stylesheets = [
        "/dist/main.min.css",
        "/assets/css/fonts.min.css",
        "/assets/css/flags.min.css",
    ]
    javascript = [
        "/assets/js/jquery-3.3.1.min.js",
        "/assets/js/autocomplete.jquery.min.js",
        "/assets/js/main.js",
    ]
    headerlogo = "assets/img/logo.png"
    footerlogo = "assets/img/enerfis-logo.png"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[outputFormats.JSON]
    baseName = "index"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
    section = ["HTML"]
    page = ["HTML"]

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[languages]
    [languages.cs]
        contentDir = "content/cs"
        languageName = "Czech"
        weight = 1
    [languages.en]
        contentDir = "content/en"
        languageName = "English"
        weight = 2
    [languages.es]
        contentDir = "content/es"
        languageName = "Spanish"
        weight = 3
    [languages.it]
        contentDir = "content/it"
        languageName = "Italian"
        weight = 4
    [languages.de]
        contentDir = "content/de"
	    languageName = "German"
	    weight = 5
    [languages.ru]
        contentDir = "content/ru"
        languageName = "Russian"
        weight = 6
    [language.fr]
        contentDir = "content/fr"
        languageName = "French"
        weight = 7