# URL Root
BaseURL = "/"

# Site title
title = "Enectiva FAQ"

# Language
LanguageCode = "en"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = "true"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Pagination
paginate = 6
paginatePath = "page"

[params]
    author = "Enectiva"
    search = true
    stylesheets = [
        "dist/main.min.css",
        "assets/css/fonts.min.css",
        "assets/css/flags.min.css"
    ]
    
    javascript = [
        "jquery-3.2.1.js",
        "horsey.min.js",
        "lunr.min.js",
        "string.min.js",
        "main.js"
    ]
    headerlogo = "assets/img/logo.png"
    footerlogo = "assets/img/enerfis-logo.png"

[taxonomies]
    tag     = "tags"
    czech   = "cs"
    english = "en"
    german  = "de"
    italian = "it"
    russian = "ru"
    spanish = "es"

[permalinks]
    es = "/:slug/:filename"
    cs = "/:slug/:filename"
    it = "/:slug/:filename"
    de = "/:slug/:filename"
    en = "/:slug/:filename"
    ru = "/:slug/:filename"

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[outputs]
    home = [
        "HTML",
        "JSON"
    ]
    page = [
        "HTML"
    ]

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[languages]
## Taxonomies for language -- Start ##
[languages.en.taxonomies]
    english = "en"
        section = "sections"
            man = "manuals"
            third-party-manual = "third-party manuals"
            installation-instruction = "installation-instructions"
                meter = "meters"
                sensor = "sensors"
                gateway = "gateways"
                converter = "converters"
                splitter = "splitters"
                concentrator = "concentrators"
    tag = "tags"

[languages.it.taxonomies]
    italian = "it"
        sezione = "sezioni"
            manuale = "manuali"
            manuale-terzo = "manuali-terzo"
            istruzione-per-l-installazione = "istruzioni-di-installazione"
                metro = "calibri"
                sensor = "sensori"
                gateway = "gateways"
                convertitore = "convertitori"
                splitter = "splitters"
                concentratore = "concentratori"
    tag = "tags"

[languages.de.taxonomies]
    german = "de"
        abschnitt = "abschnitte"
            handbuch = "handbucher"
            handbuch-dritte = "handbucher-dritte"
            installationsanweisungen = "installationsanleitung"
                meter = "lehren"
                sensor = "sensoren"
                gateway = "gateways"
                konverter = "wandler"
                weiche = "weichen"
                konzentrator = "konzentratoren"
    tag = "tags"

[languages.ru.taxonomies]
    russian = "ru"
        razdel = "razdely"
            rukovodstvo = "rukovodstva"
            tretiy-po-ekspluatatsii = "rukovodstva-tret-yego"
            instruktsiya-po-montazhu = "instruktsiya-po-ustanovke"
                shlyuz = "shlyuzy"
                metr = "manometry"
                datchik = "datchikov"
                konverter = "preobrazovateli"
                razvetvitel = "razvetviteli"
                kontsentrator = "kontsentratory"
    tag = "tags"
[languages.cs.taxonomies]
    czech = "cs"
        cast = "oddily"
            prirucka = "manualy"
            treti-manualni = "manualy-treti"
            pokyny-k-instalaci = "instrukce-k-instalaci"
                metr = "meridla"
                brana = "brany"
                senzor = "senzory"
                konvertor = "prevodniky"
                rozdelovac = "rozdelovace"
                koncentrator = "koncentratory"
    tag = "tags"


[languages.fr.taxonomies]
    french = "fr"
        section = "sections"
            manuel = "manuels"
            troisieme-manuel = "manuels-troisieme"
            instruction-d-installation = "instructions-d-installation"
                metre = "jauges"
                capteur = "capteurs"
                passerelle = "passerelles"
                convertisseur = "convertisseurs"
                diviseur = "diviseurs"
                concentrateur = "concentrateurs"
    tag = "tags"

[languages.es.taxonomies]
    spanish = "es"
        seccion = "secciones"
            manual = "manuales"
            manual-de-tercero = "manuales-de-terceros"
            instruccion-de-instalacion = "instrucciones-de-instalacion"
                sensor = "sensores"
                medidor = "medidores"
                convertidor = "convertidores"
                puerta-de-enlace = "puertas-de-enlace"
                splitter = "splitters"
                concentrador = "concentradores"
    tag = "tags"
## Taxonomies for language -- Finish ##
